import { type NextPage } from "next";
import Head from "next/head";
import { SignInButton, useUser } from "@clerk/nextjs";

import { api } from "~/utils/api";
import CreatePostWizard from "~/components/CreatePostWizard";
import PostView from "~/components/PostView";

const Home: NextPage = () => {
  const user = useUser();

  const { data, isLoading } = api.post.getAll.useQuery();

  if (isLoading || !user.isLoaded) {
    return (
      <div className="flex h-screen w-full items-center justify-center">
        Initializing app. Please wait
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center">
        <div className="h-screen w-full border-x border-slate-400 md:max-w-4xl">
          <div className="flex border-b border-slate-400 p-4">
            {!user.isSignedIn && <SignInButton />}
            {!!user.isSignedIn && <CreatePostWizard />}
          </div>
          <div>
            {data?.map((postWithAuthor) => (
              <PostView key={postWithAuthor.post.id} {...postWithAuthor} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
